name: 'lowercase'
description: 'lower case a text'
inputs:
  text: 
    description: 'the text to lower case'
    required: true
    default: 'Hello DevOps'
outputs:
  text:
    description: 'The text in lower case'
    value: ${{ steps.lower-step.outputs.text }}
runs:
  using: "composite"
  steps:
    - name: Start to lower text ${{ inputs.text }}
      run: |
        ./lower.sh 'text=${{ inputs.text }}' >> $GITHUB_OUTPUT
      shell: bash
      id: lower-step

